fracking_tools/document_tools/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'document_tools'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^ajax/check-task-status/', views.check_task_status, name='check_task_status'),    
    # url(r'^results/$', views.results_view, name='results'),
    
    url(r'^compare-documents/$', views.compare_documents_view, name='compare_documents'),
    url(r'^compare-documents/compare/$', views.compare_documents_now_view, name='compare_documents_now'),
    url(r'^compare-documents/download/$', views.download_document_comparisons_view, name='download_comparisons'),

    url(r'^tag-documents-keywords/$', views.tag_documents_keywords_view, name='tag_documents_keywords'),
    url(r'^tag-documents-keywords/tag$', views.tag_documents_keywords_now_view, name='tag_documents_keywords_now'),
    
    url(r'^tag-documents-ner/$', views.tag_documents_ner_view, name='tag_documents_ner'),
    url(r'^tag-documents-ner/tag$', views.tag_documents_ner_now_view, name='tag_documents_ner_now'),

    url(r'^compute-document-statistics/$', views.compute_document_statistics_view, name='compute_document_statistics'),
    url(r'^compute-document-statistics/compute$', views.compute_document_statistics_now_view, name='compute_document_statistics_now'),

    url(r'^compute-document-statistics/download$', views.download_document_analysis_view, name='download_document_analysis'),


    url(r'^download-tagged-documents$', views.download_tagged_documents_view, name='download_tagged_documents'),



    # download_keywords_tagged_documents_view
    # url(r'^compare-documents/compare/$', views.compare_documents_now_view, name='compare_documents_now'),
    # url(r'^compare-documents/download/$', views.download_document_comparisons_view, name='download_comparisons'),
    

    # tag_documents_keywords_view
    # url(r'^events-networks/$', views.build_events_networks_view, name='build_enets'),
    # url(r'^events-networks/build/$', views.build_events_networks_now_view, name='build_enets_now'),
    
    # url(r'^pairs-networks/$', views.build_pairs_networks_view, name='build_pnets'),
    # url(r'^pairs-networks/build/$', views.build_pairs_networks_now_view, name='build_pnets_now'),
    
    # url(r'^compare-networks/$', views.compare_networks_view, name='compare_nets'),
    # url(r'^compare-networks/compare$', views.compare_networks_now_view, name='compare_nets_now'),
    # url(r'^compare-networks/download$', views.download_network_comparisons_view, name='download_comparisons'),

    # url(r'^download/$', views.download_networks_view, name='download_networks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/documentation/urls.py
from django.conf.urls import url
from . import views


app_name = 'documentation'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^edit/$', views.edit_view, name='edit'),
    url(r'^add-category/$', views.add_category_view, name='add_category'),
    url(r'^add-section/$', views.add_section_view, name='add_section'),
]

fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('fthome.urls')),
    url(r'^network-tools/', include('network_tools.urls')),
    url(r'^document-tools/', include('document_tools.urls')),
    url(r'^documentation/', include('documentation.urls')),
    url(r'^admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fracking_tools/fthome/urls.py
from django.conf.urls import url
from . import views


app_name = 'fthome'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
]

fracking_tools/network_tools/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'network_tools'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^ajax/check-task-status/', views.check_task_status, name='check_task_status'),    
    url(r'^results/$', views.results_view, name='results'),
    
    url(r'^events/$', views.build_events_view, name='build_events'),
    url(r'^events/build/$', views.build_events_now_view, name='build_events_now'),
    url(r'^events/download/$', views.download_events_file_view, name='download_events'),
    
    url(r'^events-networks/$', views.build_events_networks_view, name='build_enets'),
    url(r'^events-networks/build/$', views.build_events_networks_now_view, name='build_enets_now'),
    
    url(r'^pairs-networks/$', views.build_pairs_networks_view, name='build_pnets'),
    url(r'^pairs-networks/build/$', views.build_pairs_networks_now_view, name='build_pnets_now'),
    
    url(r'^compare-networks/$', views.compare_networks_view, name='compare_nets'),
    url(r'^compare-networks/compare$', views.compare_networks_now_view, name='compare_nets_now'),
    url(r'^compare-networks/download$', views.download_network_comparisons_view, name='download_comparisons'),

    url(r'^download/$', views.download_networks_view, name='download_networks'),

    # Convert adjacency matrices to R-networks
    
    url(r'^convert-to-r-networks/$', views.convert_matrices_to_rnetworks_view, name='convert_to_rnetworks'),
    url(r'^convert-to-r-networks/convert$', views.convert_matrices_to_rnetworks_now_view, name='convert_to_rnetworks_now'),
    url(r'^convert-to-r-networks/download$', views.download_rnetworks_view, name='download_rnetworks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/templates/ftglobal/footer.html
<div class="container text-center">
  <div class="row">
    <div class="col-sm-12">
      <i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:rahuezo@ucdavis.edu">rahuezo@ucdavis.edu</a>
    </div>
    <!-- <div class="col-sm-6">
      <i class="fa fa-globe" aria-hidden="true"></i> <a href="http://rudyhuezo.work">rudyhuezo.work</a>
    </div> -->
  </div>
  <div class="row mt-4">
    <div class="col-sm-12 text-center text-muted">
      <p class="lead">
        <i class="fa fa-code" aria-hidden="true"></i> with <i class="fa fa-heart" aria-hidden="true"></i> by <strong>Rudy Huezo</strong>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 text-muted">
      © 2019 Fracking Tools All rights reserved.
    </div>
  </div>
</div>

fracking_tools/templates/ftglobal/head.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

<!-- Font Awesome -->
{# <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> #}
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

<!-- Local CSS -->
<link rel="stylesheet" href="{% static 'ftglobal/css/style.css' %}">

<!-- Site Favicon -->
<link rel="shortcut icon" type="image/png" href="{% static 'ftglobal/img/fracking-tools logo.png' %}"/>

fracking_tools/templates/ftglobal/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-dark navbar-bg-custom sticky-top">
  <a class="navbar-brand" href="{% url 'fthome:index' %}">
    <img src="{% static 'ftglobal/img/fracking-tools logo.png' %}" alt="Fracking Tools Logo">
    Fracking Tools
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mr-2 text-center">
      <li class="nav-item m-2 dropdown">
        <a class="btn btn-light btn-block dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Network Tools
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'network_tools:build_events' %}">Build Events from Files</a>
          <a class="dropdown-item" href="{% url 'network_tools:build_enets' %}">Build Networks from Events</a>
          <a class="dropdown-item" href="{% url 'network_tools:build_pnets' %}">Build Networks from Node Pairs</a>
          <a class="dropdown-item" href="{% url 'network_tools:compare_nets' %}">Compare Networks</a>
          <a class="dropdown-item" href="{% url 'network_tools:convert_to_rnetworks' %}">Convert Matrices to R-Networks</a>
        </div>
      </li>

      <li class="nav-item m-2 dropdown">
        <a class="btn btn-light btn-block dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Document Tools
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'document_tools:compare_documents' %}">Compare Documents</a>
          <a class="dropdown-item" href="{% url 'document_tools:tag_documents_keywords' %}">Tag Documents for Keywords</a>
          <a class="dropdown-item" href="{% url 'document_tools:tag_documents_ner' %}">Tag Documents Using NER</a>
          <a class="dropdown-item" href="{% url 'document_tools:compute_document_statistics' %}">Compute Document Statistics</a>
        </div>
      </li>
      <li class="nav-item m-2">
        <a href="{% url 'documentation:index' %}" class="btn btn-warning btn-block"><i class="fas fa-book"></i> Documentation</a>
      </li>
    </ul>
  </div>
</nav>