fracking_tools/document_tools/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'document_tools'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^ajax/check-task-status/', views.check_task_status, name='check_task_status'),    
    # url(r'^results/$', views.results_view, name='results'),
    
    url(r'^compare-documents/$', views.compare_documents_view, name='compare_documents'),
    url(r'^compare-documents/compare/$', views.compare_documents_now_view, name='compare_documents_now'),
    url(r'^compare-documents/download/$', views.download_document_comparisons_view, name='download_comparisons'),

    url(r'^tag-documents-keywords/$', views.tag_documents_keywords_view, name='tag_documents_keywords'),
    url(r'^tag-documents-keywords/tag$', views.tag_documents_keywords_now_view, name='tag_documents_keywords_now'),
    
    url(r'^tag-documents-ner/$', views.tag_documents_ner_view, name='tag_documents_ner'),
    url(r'^tag-documents-ner/tag$', views.tag_documents_ner_now_view, name='tag_documents_ner_now'),

    url(r'^compute-document-statistics/$', views.compute_document_statistics_view, name='compute_document_statistics'),
    url(r'^compute-document-statistics/compute$', views.compute_document_statistics_now_view, name='compute_document_statistics_now'),

    url(r'^compute-document-statistics/download$', views.download_document_analysis_view, name='download_document_analysis'),


    url(r'^download-tagged-documents$', views.download_tagged_documents_view, name='download_tagged_documents'),



    # download_keywords_tagged_documents_view
    # url(r'^compare-documents/compare/$', views.compare_documents_now_view, name='compare_documents_now'),
    # url(r'^compare-documents/download/$', views.download_document_comparisons_view, name='download_comparisons'),
    

    # tag_documents_keywords_view
    # url(r'^events-networks/$', views.build_events_networks_view, name='build_enets'),
    # url(r'^events-networks/build/$', views.build_events_networks_now_view, name='build_enets_now'),
    
    # url(r'^pairs-networks/$', views.build_pairs_networks_view, name='build_pnets'),
    # url(r'^pairs-networks/build/$', views.build_pairs_networks_now_view, name='build_pnets_now'),
    
    # url(r'^compare-networks/$', views.compare_networks_view, name='compare_nets'),
    # url(r'^compare-networks/compare$', views.compare_networks_now_view, name='compare_nets_now'),
    # url(r'^compare-networks/download$', views.download_network_comparisons_view, name='download_comparisons'),

    # url(r'^download/$', views.download_networks_view, name='download_networks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('fthome.urls')),
    url(r'^network-tools/', include('network_tools.urls')),
    url(r'^document-tools/', include('document_tools.urls')),
    url(r'^documentation/', include('documentation.urls')),
    url(r'^admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fracking_tools/fthome/urls.py
from django.conf.urls import url
from . import views


app_name = 'fthome'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
]

fracking_tools/document_tools/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

fracking_tools/document_tools/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.http import JsonResponse

from utils import configuration
from documentation.models import Section

from celery.result import AsyncResult
from fracking_tools.celery import app

import csv, io, zipfile


from utils import configuration
from .tasks import compare_documents, tag_documents_keywords, tag_documents_ner, compute_document_statistics


def index_view(request): 
    context = {
        'compare_documents': configuration.COMPARE_DOCS_CARD, 
        'tag_documents_kwds': configuration.TAG_DOCS_KEYWORDS_CARD,
        'tag_documents_ner': configuration.TAG_DOCS_NER_CARD,
        'doc_stats': configuration.DOC_STATS_CARD
    }
    return render(request, 'document_tools/index.html', context)


# Compare documents

def compare_documents_view(request): 
    context = {
        'section': Section.objects.filter(name='Compare Documents')[0],
    }
    return render(request, 'document_tools/compare_documents/compare_documents.html', context)


def compare_documents_now_view(request):
    response = redirect('document_tools:compare_documents')

    if request.method == 'POST' and request.FILES and request.POST.get('output-csv'):
        output_csv_file = request.POST.get('output-csv')
        files = request.FILES.getlist('input-files')
        results = compare_documents.delay(files)
        # results = compare_documents(files)

        # print "Results: ", results

        response['Location'] += '?task={}&csv={}'.format(results, output_csv_file)
    return response


def download_document_comparisons_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('csv'):         
        task_id = request.GET.get('task')
        output_csv = request.GET.get('csv')
        
        task = AsyncResult(task_id, app=app)
        
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment;filename="{}.csv"'.format(output_csv)
        
        writer = csv.writer(response)
        writer.writerow(['File A', 'File B', 'Cosine Similarity', 'Jaccard Similarity'])

        for row in task.get(): 
            writer.writerow(row)
        return response
    return redirect('document_tools:compare_documents')

# End Compare documents


# Tag Documents for Keywords

def tag_documents_keywords_view(request): 
    context = {
        'section': Section.objects.filter(name='Tag Documents for Keywords')[0],
    }
    return render(request, 'document_tools/tag_documents_keywords/tag_documents.html', context)


def tag_documents_keywords_now_view(request):
    response = redirect('document_tools:tag_documents_keywords')

    if request.method == 'POST' and request.FILES and request.POST.get('output-zip') and request.POST.get('keywords-list'):
        output_zip_file = request.POST.get('output-zip')
        files = request.FILES.getlist('input-files')
        keywords = [kw.strip() for kw in request.POST.get('keywords-list').split(',')]

        results = tag_documents_keywords.delay(files, keywords)

        response['Location'] += '?task={}&zip={}'.format(results, output_zip_file)
    return response

# End Tag documents for keywords


# Tag Documents Using NER

def tag_documents_ner_view(request): 
    context = {
        'section': Section.objects.filter(name='Tag Documents Using Stanford\'s Named Entity Recognizer (NER)')[0],
    }
    return render(request, 'document_tools/tag_documents_ner/tag_documents.html', context)


def tag_documents_ner_now_view(request):
    response = redirect('document_tools:tag_documents_ner')

    if request.method == 'POST' and request.FILES and request.POST.get('output-zip'):
        output_zip_file = request.POST.get('output-zip')
        files = request.FILES.getlist('input-files')

        results = tag_documents_ner.delay(files)

        response['Location'] += '?task={}&zip={}'.format(results, output_zip_file)
    return response

# End Tag documents using NER


# Compute Document Statistics

def compute_document_statistics_view(request): 
    context = {
        'section': Section.objects.filter(name='Compute Document Statistics')[0]
    }
    return render(request, 'document_tools/document_statistics/document_statistics.html', context)


def compute_document_statistics_now_view(request):
    response = redirect('document_tools:compute_document_statistics')

    if request.method == 'POST' and request.FILES and request.POST.get('output-csv') and request.POST.get('keywords-list'):
        output_csv_file = request.POST.get('output-csv')
        files = request.FILES.getlist('input-files')
        keywords = [kw.strip() for kw in request.POST.get('keywords-list').split(',')]

        results = compute_document_statistics.delay(files, keywords)

        response['Location'] += '?task={}&csv={}'.format(results, output_csv_file)
    return response


def download_document_analysis_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('csv'):         
        task_id = request.GET.get('task')
        output_csv = request.GET.get('csv')
        
        task = AsyncResult(task_id, app=app)
        
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment;filename="{}.csv"'.format(output_csv)
        
        writer = csv.writer(response)
        
        for row in task.get(): 
            writer.writerow(row)
        return response
    return redirect('document_tools:compute_document_statistics')

# End Compute document statistics 



# Download tagged documents 

def download_tagged_documents_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('zip'):         
        task_id = request.GET.get('task')
        output_zip = request.GET.get('zip')
        
        task = AsyncResult(task_id, app=app)

        zip_io = io.BytesIO()

        # fill zip file 
        with zipfile.ZipFile(zip_io, mode='w', compression=zipfile.ZIP_DEFLATED) as zip_file: 
            # Create csv io here 

            for fname, content in task.get(): 
                zip_file.writestr(fname, content)
                
        # response will be zip file 
        response = HttpResponse(zip_io.getvalue(), content_type='application/x-zip-compressed')
        response['Content-Disposition'] = 'attachment;filename="{}.zip"'.format(output_zip)
        response['Content-Length'] = zip_io.tell()

        print "Current task ID: ", task_id
        print "Output Zip: ", output_zip
        return response
    return redirect('document_tools:index')


def check_task_status(request): 
    task_id = request.GET.get('task-id')
    task = AsyncResult(task_id, app=app)    
    
    return JsonResponse({'status': task.status, 'traceback': task.traceback })

fracking_tools/templates/document_tools/document_statistics/document_statistics.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Fracking Tools: Tag Documents for Keywords</title>
    {% include 'ftglobal/head.html' %}
  </head>
  <body>
    {% include 'ftglobal/navbar.html' %}
    <div id="wrapper">
      <div id="header">
        {% include 'document_tools/document_statistics/jumbotron.html' %}
      </div>
      <div id="content">
          <div class="container text-center">
            {% include 'document_tools/read_docs.html' %}
            <form action="{% url 'document_tools:compute_document_statistics_now' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'document_tools/document_statistics/steps.html' %}
            </form>
          </div>
        </div>
      <div id="footer">
        {% include 'ftglobal/footer.html' %}
      </div>
    </div>

   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <!-- Main JS Code -->
    <script src="{% static 'ftglobal/js/main.js' %}" charset="utf-8"></script>
    <script src="{% static 'ftglobal/js/misc.js' %}" charset="utf-8"></script>

    {% if request.GET.task %}
      <script>
        let interval = 1000; 
        let intervalId; 
        let taskUrl = '{% url "document_tools:check_task_status" %}';
        let taskData = '{{ request.GET.task }}'; 
        let windowHomeUrl = '{% url "document_tools:compute_document_statistics" %}'; 
        let downloadUrl = '{% url "document_tools:download_document_analysis" %}?task={{ request.GET.task }}&csv={{ request.GET.csv }}'; 
        let successMessage = 'Finished analyzing documents!'; 
        let downloadMessage = 'Downloaded analyzed documents! Resetting documents analyzer...'; 

        $(document).ready(function(){
          
          // Scroll window to bottom to show that process is running
          window.scrollTo(0,document.body.scrollHeight);

          // Show user that task is starting 
          $('.task-status').html('Currently comparing networks. <span class="text-danger"><strong>Do not refresh the page!</strong></span>'); 

          // Run the first task status check
          setTimeout(checkTaskStatus, 0); 

          // Start an interval to check task status regularly 
          intervalId = setInterval(function() {
            checkTaskStatus(taskUrl, taskData);           
          }, interval); 
        });
      </script>
    {% endif %}    
  </body>
</html>

fracking_tools/templates/document_tools/document_statistics/jumbotron.html
<div class="jumbotron jumbotron-fluid" id="home-banner">
    <div class="container text-center">
        <h1 class="display-4 text-dark">Compute Document Statistics</h1>
        <p class="lead text-dark">Compute word count, reading level, keyword frequency, 
            and sentiment analysis for one or many documents.</p>
        <hr class="my-4">
        <div class="row my-4">
            <div class="col-sm-4">
                <a href="{% url 'document_tools:compare_documents' %}" class="btn btn-dark btn-block my-1">Compare Documents</a>
            </div>
            <div class="col-sm-4">
                <a href="{% url 'document_tools:tag_documents_keywords' %}" class="btn btn-dark btn-block my-1">Tag Documents for Keywords</a>
            </div>
            <div class="col-sm-4">
                <a href="{% url 'document_tools:tag_documents_ner' %}" class="btn btn-dark btn-block my-1">Tag Documents with NER</a>
            </div>
        </div>
    </div>
</div>

fracking_tools/templates/document_tools/document_statistics/steps.html
<div class="card w-100 my-4">
    <div class="card-body text-left">        
        <h4 class="card-title mb-4">1. Upload Files</h4>
        <p class="card-text">Upload the files you want to analyze. These files can only be <strong>.txt</strong> or <strong>.docx</strong>.</p>        
    </div>
    <div class="card-footer">
        <div class="form-group">
            <input class="form-control" type="file" id="file-input" name="input-files" accept=".txt,.docx" multiple required>
        </div>
    </div>
</div>

<div class="card w-100 my-4">
    <div class="card-body text-left">
        <h4 class="card-title mb-4">2. Choose Keywords</h4>
        <p class="card-text">Enter a list of keywords separated by commas.</p>        
    </div>
    <div class="card-footer">
        <div class="form-group">
            <input class="form-control" type="text" id="keywords-list" name="keywords-list" placeholder="e.g. Fracking, hydraulic fracturing, hydraulic fracking, shale gas, etc." required>
        </div>
    </div>
</div>  

<div class="card w-100 my-4">
    <div class="card-body text-left">
        <h4 class="card-title mb-4">3. Choose Output <strong>.csv</strong> Name</h4>
        <p class="card-text">Enter a name for the output .csv file containing all results.</p>        
    </div>
    <div class="card-footer">
        <div class="form-group">
            <input class="form-control" type="text" id="output-csv" name="output-csv" placeholder="e.g. My Documents, Analyzed Documents, Analyzed Meeting Minutes, etc." required>
        </div>
    </div>
</div>  

<div class="card w-100 my-4">
    <div class="card-body text-left">
        <h4 class="card-title mb-4">4. Compute Document Statistics</span></h4>
        <p class="card-text task-status">Click below to start computing document statistics.</p>
    </div>
    <div class="card-footer">
        <div class="form-group" id="run-btn">
            {% if request.GET.task %}
                <button type="submit" class="btn btn-dark btn-block" name="button"> 
                    Computing <i class="fas fa-spinner fa-spin"></i>
                </button>
            {% else %}
                <button type="submit" class="btn btn-dark btn-block" name="button"> 
                    Compute <i class="fas fa-chart-bar" aria-hidden="true"></i>
                </button>
            {% endif %}
        </div>
    </div>
</div>