fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('fthome.urls')),
    url(r'^network-tools/', include('network_tools.urls')),
    url(r'^document-tools/', include('document_tools.urls')),
    url(r'^documentation/', include('documentation.urls')),
    url(r'^admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fracking_tools/fthome/urls.py
from django.conf.urls import url
from . import views


app_name = 'fthome'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
]

fracking_tools/network_tools/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'network_tools'


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^ajax/check-task-status/', views.check_task_status, name='check_task_status'),    
    url(r'^results/$', views.results_view, name='results'),
    
    url(r'^events/$', views.build_events_view, name='build_events'),
    url(r'^events/build/$', views.build_events_now_view, name='build_events_now'),
    url(r'^events/download/$', views.download_events_file_view, name='download_events'),
    
    url(r'^events-networks/$', views.build_events_networks_view, name='build_enets'),
    url(r'^events-networks/build/$', views.build_events_networks_now_view, name='build_enets_now'),
    
    url(r'^pairs-networks/$', views.build_pairs_networks_view, name='build_pnets'),
    url(r'^pairs-networks/build/$', views.build_pairs_networks_now_view, name='build_pnets_now'),
    
    url(r'^compare-networks/$', views.compare_networks_view, name='compare_nets'),
    url(r'^compare-networks/compare$', views.compare_networks_now_view, name='compare_nets_now'),
    url(r'^compare-networks/download$', views.download_network_comparisons_view, name='download_comparisons'),

    url(r'^download/$', views.download_networks_view, name='download_networks'),

    # Convert adjacency matrices to R-networks
    
    url(r'^convert-to-r-networks/$', views.convert_matrices_to_rnetworks_view, name='convert_to_rnetworks'),
    url(r'^convert-to-r-networks/convert$', views.convert_matrices_to_rnetworks_now_view, name='convert_to_rnetworks_now'),
    url(r'^convert-to-r-networks/download$', views.download_rnetworks_view, name='download_rnetworks'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/network_tools/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

fracking_tools/network_tools/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.http import JsonResponse
from django.http import FileResponse

import io

from utils import configuration
from documentation.models import Section

from networktools.files.readers import FileReader

from .tasks import build_events_from_files, build_event_networks, build_pairs_networks, compare_networks, convert_matrices_to_rnetworks
from celery.result import AsyncResult
from fracking_tools.celery import app

import csv, io, zipfile


def index_view(request):
    context = {
        'event_networks_card': configuration.BUILD_NETWORKS_FROM_EVENTS_CARD,
        'pair_networks_card': configuration.BUILD_NETWORKS_FROM_PAIRS_CARD,
        'compare_networks': configuration.COMPARE_NETWORKS_CARD,
        'build_events': configuration.BUILD_EVENTS_FROM_FILES_CARD,
        'convert_to_r_networks': configuration.CONVERT_MATRICES_TO_R_NETWORKS
    }

    return render(request, 'network_tools/index.html', context)


def results_view(request): 
    context = {}

    if request.method == 'GET': 
        task_id = request.GET.get('task-id')  
        if task_id: 
            work = AsyncResult(task_id, app=app)
            context['task_id'] = task_id
            context['work'] = work

    return render(request, 'network_tools/results.html', context)


# Events builder parts 

def build_events_view(request):
    context = {
        'section': Section.objects.filter(name='Build Events From Files')[0],
    }
    return render(request, 'network_tools/events_builder/events_builder.html', context)


def build_events_now_view(request):
    response = redirect('network_tools:build_events')

    if request.method == 'POST' and request.FILES and request.POST.get('output-events-csv'):
        output_csv_file = request.POST.get('output-events-csv')
        files = request.FILES.getlist('input-files')
        results = build_events_from_files.delay(files)

        response['Location'] += '?task={}&csv={}'.format(results, output_csv_file)
    return response


def download_events_file_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('csv'):         
        task_id = request.GET.get('task')
        output_csv = request.GET.get('csv')
        
        task = AsyncResult(task_id, app=app)
        
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment;filename="{}.csv"'.format(output_csv)
        
        writer = csv.writer(response)

        for row in task.get(): 
            writer.writerow(row)
        return response
    return redirect('network_tools:build_events')

# End events builder parts 

# Events networks parts

def build_events_networks_view(request):
    context = {
        'section': Section.objects.filter(name='Build Networks From Events')[0],
    }
    return render(request, 'network_tools/events_networks/events_networks.html', context)


def build_events_networks_now_view(request):
    response = redirect('network_tools:build_enets')

    if request.method == 'POST' and request.FILES and request.POST.get('output-zip'):
        output_zip = request.POST.get('output-zip')
        header_state = True if request.POST.get('header-state') else False
        weighted_state = True if request.POST.get('weighted-state') else False

        
        files = request.FILES.getlist('input-files')
        results = build_event_networks.delay(files, header_state, weighted_state)

        response['Location'] += '?task={}&zip={}'.format(results, output_zip)
    return response

# End events networks parts 

# Pairs networks parts 

def build_pairs_networks_view(request):
    context = {
        'section': Section.objects.filter(name='Build Networks From Node Pairs')[0],
    }
    return render(request, 'network_tools/pairs_networks/pairs_networks.html', context)


def build_pairs_networks_now_view(request):
    response = redirect('network_tools:build_pnets')

    if request.method == 'POST' and request.FILES and request.POST.get('output-zip'):
        output_zip = request.POST.get('output-zip')
        header_state = True if request.POST.get('header-state') else False

        files = request.FILES.getlist('input-files')
        results = build_pairs_networks.delay(files, header_state)

        response['Location'] += '?task={}&zip={}'.format(results, output_zip)
    return response

# End pairs networks parts 

# Convert matrices to R-Networks 

def convert_matrices_to_rnetworks_view(request):
    context = {
        'section': Section.objects.filter(name='Convert Adjacency Matrices to R-Networks')[0],
    }
    return render(request, 'network_tools/convert_networks/convert_networks.html', context)

def convert_matrices_to_rnetworks_now_view(request):
    response = redirect('network_tools:convert_to_rnetworks')

    if request.method == 'POST' and request.FILES and request.POST.get('output-rda'):
        output_rda_file = request.POST.get('output-rda')
        files = request.FILES.getlist('input-files')
        results = convert_matrices_to_rnetworks.delay(files)

        response['Location'] += '?task={}&rda={}'.format(results, output_rda_file)
    return response

def download_rnetworks_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('rda'):         
        task_id = request.GET.get('task')
        output_rda = request.GET.get('rda')
        
        task = AsyncResult(task_id, app=app)
        
        stream = io.BytesIO(task.get())

        response = FileResponse(stream, content_type='application/octet-stream')
        response['Content-Disposition'] = 'inline;filename="{}.rda"'.format(output_rda)
        
        return response
    return redirect('network_tools:convert_to_rnetworks')

# End convert matrices to R-Networks

# Download networks

def download_networks_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('zip'):         
        task_id = request.GET.get('task')
        output_zip = request.GET.get('zip')
        
        task = AsyncResult(task_id, app=app)

        zip_io = io.BytesIO()

        # fill zip file 
        with zipfile.ZipFile(zip_io, mode='w', compression=zipfile.ZIP_DEFLATED) as zip_file: 
            # Create csv io here 

            for fname, matrix in task.get(): 
                csv_io = io.BytesIO()
                matrix.to_csv(csv_io, sep=str(u',').encode('utf-8'), index=False)
                zip_file.writestr(fname, csv_io.getvalue())
                
        # response will be zip file 
        response = HttpResponse(zip_io.getvalue(), content_type='application/x-zip-compressed')
        response['Content-Disposition'] = 'attachment;filename="{}.zip"'.format(output_zip)
        response['Content-Length'] = zip_io.tell()
    
        return response
    return redirect('network_tools:index')

# End download networks


# Compare networks parts

def compare_networks_view(request):
    context = {
        'section': Section.objects.filter(name='Compare Networks')[0],
    }
    return render(request, 'network_tools/compare_networks/compare_networks.html', context)


def compare_networks_now_view(request):
    response = redirect('network_tools:compare_nets')

    if request.method == 'POST' and request.FILES and request.POST.get('output-zip'):
        networksA_label = request.POST.get('networkA-label')
        networksA_files = request.FILES.getlist('networkA-files')

        networksB_label = request.POST.get('networkB-label')
        networksB_files = request.FILES.getlist('networkB-files')

        output_zip = request.POST.get('output-zip')

        files = (networksA_files, networksB_files)

        results = compare_networks.delay(files, networksA_label, networksB_label)

        response['Location'] += '?task={}&zip={}'.format(results, output_zip)
    return response


def download_network_comparisons_view(request): 
    if request.method == 'GET' and request.GET.get('task') and request.GET.get('zip'):         
        task_id = request.GET.get('task')
        output_zip = request.GET.get('zip')
        
        task = AsyncResult(task_id, app=app)

        zip_io = io.BytesIO()

        # fill zip file 
        with zipfile.ZipFile(zip_io, mode='w', compression=zipfile.ZIP_DEFLATED) as zip_file: 
            # Create csv io here 

            for fname, rows in task.get(): 
                csv_io = io.BytesIO()
                
                writer = csv.writer(csv_io)
                writer.writerows(rows)

                zip_file.writestr(fname, csv_io.getvalue())
                
        # response will be zip file 
        response = HttpResponse(zip_io.getvalue(), content_type='application/x-zip-compressed')
        response['Content-Disposition'] = 'attachment;filename="{}.zip"'.format(output_zip)
        response['Content-Length'] = zip_io.tell()

        return response
    return redirect('network_tools:index')


# End compare networks 


def check_task_status(request): 
    task_id = request.GET.get('task-id')
    task = AsyncResult(task_id, app=app)    
    return JsonResponse({'status': task.status, 'traceback': task.traceback })

fracking_tools/templates/network_tools/pairs_networks/jumbotron.html
<div class="jumbotron jumbotron-fluid" id="home-banner">
  <div class="container text-center">
    <h1 class="display-4 text-dark">Build Networks From Node Pairs</h1>
    <p class="lead text-dark">Build one or many networks from <strong>.csv</strong> node pairs spreadsheets.</p>
    <hr class="my-4">
    <div class="row my-4">
      <div class="col-sm-3">
        <a href="{% url 'network_tools:build_enets' %}" class="btn btn-dark btn-block my-1">Build Events from Files</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'network_tools:build_enets' %}" class="btn btn-dark btn-block my-1">Build Networks from Events</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'network_tools:compare_nets' %}" class="btn btn-dark btn-block my-1">Compare Networks</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'network_tools:convert_to_rnetworks' %}" class="btn btn-dark btn-block my-1">Convert Matrices to R-Networks</a>
      </div>
    </div>
  </div>
</div>

fracking_tools/templates/network_tools/pairs_networks/pairs_networks.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Fracking Tools: Home</title>
    {% include 'ftglobal/head.html' %}
  </head>
  <body>
    {% include 'ftglobal/navbar.html' %}
    <div id="wrapper">
      <div id="header">
        {% include 'network_tools/pairs_networks/jumbotron.html' %}
      </div>
      <div id="content">
        <div class="container text-center">
          {% include 'network_tools/read_docs.html' %}
          <form action="{% url 'network_tools:build_pnets_now' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'network_tools/pairs_networks/steps.html' %}
          </form>
        </div>
      </div>
      <div id="footer">
        {% include 'ftglobal/footer.html' %}
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <!-- Main JS Code -->
    <script src="{% static 'ftglobal/js/main.js' %}" charset="utf-8"></script>
    <script src="{% static 'ftglobal/js/misc.js' %}" charset="utf-8"></script>

    {% if request.GET.task %}
      <script>
        let interval = 1000; 
        let intervalId; 
        let taskUrl = '{% url "network_tools:check_task_status" %}';
        let taskData = '{{ request.GET.task }}'; 
        let windowHomeUrl = '{% url "network_tools:build_pnets" %}'; 
        let downloadUrl = '{% url "network_tools:download_networks" %}?task={{ request.GET.task }}&zip={{ request.GET.zip }}'; 
        let successMessage = 'Finished building networks!'; 
        let downloadMessage = 'Downloaded networks! Resetting node pairs networks builder...'; 

        $(document).ready(function(){
          
          // Scroll window to bottom to show that process is running
          window.scrollTo(0,document.body.scrollHeight);

          // Show user that task is starting 
          $('.task-status').html('Currently building networks from node pairs files. <span class="text-danger"><strong>Do not refresh the page!</strong></span>'); 

          // Run the first task status check
          setTimeout(checkTaskStatus, 0); 

          // Start an interval to check task status regularly 
          intervalId = setInterval(function() {
            checkTaskStatus(taskUrl, taskData);           
          }, interval); 
        });
      </script>
      {% else %}
      <script>
        $(document).ready(function(){
          $('#header-check').on('change', function(){
            if(this.checked) {
              $(this).val('True'); 
            } else {
              $(this).val('False'); 
            }
          });
        }); 
      </script>
    {% endif %} 
  </body>
</html>

fracking_tools/templates/network_tools/pairs_networks/steps.html
<div class="card w-100 my-4">
        <div class="card-body text-left">
            <h4 class="card-title mb-4">1. Upload Files</h4>
            <p class="card-text">Upload one or multiple <strong>.csv</strong> node pairs files (LINK TO NODE PAIRS FILES).</p>        
        </div>
        <div class="card-footer">
            <div class="form-group">
                <input class="form-control" type="file" id="file-input" name="input-files" accept=".csv" multiple required>
            </div>
        </div>
    </div>
    
    <div class="card w-100 my-4">
        <div class="card-body text-left">
            <h4 class="card-title mb-4">2. Node Pairs Files Header Check</h4>    
            <div class="form-group">
                <div class="form-check px-4">
                    <input class="form-check-input" type="checkbox" id="header-check" name="header-state" value="">
                    <label class="form-check-label" for="header-check">
                        Check this box if all node pairs files contain headers as the first row.
                    </label>
                </div>   
            </div>
        </div>
    </div>
    
    <div class="card w-100 my-4">
        <div class="card-body text-left">
            <h4 class="card-title mb-4">3. Choose Output <strong>.zip</strong> Name</h4>
            <p class="card-text">Enter a name for the output <strong>.zip</strong> file containing all resulting networks.</p>        
        </div>
        <div class="card-footer">
            <div class="form-group">
                <input class="form-control" type="text" id="output-zip" name="output-zip" placeholder="e.g. My Newspaper Matrices, Meeting Minute Matrices, N Networks, MM Networks, etc." required>
            </div>
        </div>
    </div>  
    
    <div class="card w-100 my-4">
        <div class="card-body text-left">
            <h4 class="card-title mb-4">3. Build Node Pairs Networks</span></h4>
            <p class="card-text task-status">Click below to start building networks.</p>
        </div>
        <div class="card-footer">
            <div class="form-group" id="run-btn">
                {% if request.GET.task %}
                    <button type="submit" class="btn btn-dark btn-block" name="button"> 
                        Building <i class="fas fa-spinner fa-spin"></i>
                    </button>
                {% else %}
                    <button type="submit" class="btn btn-dark btn-block" name="button"> 
                        Build <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    </button>
                {% endif %}
            </div>
        </div>
    </div>